### ISSUE TITLE
Τέλος διαδικασίας

### ISSUE THREAD

**Issue by jsalatas** [iosifidis/kovei-covid#1]
> Όταν τελειώσει με το κατάστημα, μπορεί να σκανάρει ένα qr βγαίνοντας ώστε να αφαιρούνται τα άτομα από αυτά που είναι στο κατάστημα.

Αυτό θα πρότεινα να συνδεθει καπως με την πληρωμη, με το σκεπτικό ότι ο πελατης βγαίνοντας το πιο πιθανό ειναι να μην προβει σε καποια ενεργεια. 

Θα πορουσε ας πουμε κατα την εισοδο η εφαρμογη να προμηθευει τον πελάτη με ενα QR code (ας το πούμε "κωδικός πελάτη"), το οποίο στη συνεχεια θα σκαναρει ο ταμίας κατα την πληρωμη, με την λογικη ότι αν καποιος "κωδικός πελάτη" εχει πληρωθει τότε ειναι αρκετα ασφαλες να θεωρησουμε ότι ο πελάτης εχει αποχωρησει από το καταστημα.

**Comment by iosifidis** [comment]
Η λογική λέει αυτό. Δεν είναι όλες οι περιπτώσεις όμως που αγοράζει κάτι. Απλά θα μπει να κοιτάξει. Αλλά θα βάλω υποπερίπτωση εάν αγοράσει κάτι, να αφαιρείται κατά την πληρωμή,
